on:
  push:
    branches:
      - main

name: Deploy to AWS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build
        id: build
        run: |
          npm prune --production
          mkdir build
          zip -r build/latest.zip src

      - name: Upload to S3
        id: upload
        run: |
          aws s3 cp build/latest.zip s3://fiap-hello-world-12dvp/latest.zip
